WebApplication4/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using WebApplication4.Data;
using WebApplication4.Models;
using WebApplication4.Utility;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace WebApplication4.Controllers
{
    [Authorize]
    public class DashBoardController : Controller
    {
        //private static List<Product> products=new List<Product>();
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment host;
        public DashBoardController(ApplicationDbContext db,IHostingEnvironment host)
        {
            _db = db;
            this.host = host;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles =RL.RoleAdmin)]
        public IActionResult AddProduct()
        {
            
            return View();

        }
        [HttpPost]
		[Authorize(Roles = RL.RoleAdmin)]
		public IActionResult AddProduct(Product product)
        {
            if (product.ProductImage != null)
            {
                string ImageFolder = Path.Combine(host.WebRootPath, "images");
                string Imagepath = Path.Combine(ImageFolder, product.ProductImage.FileName);
                product.ProductImage.CopyTo(new FileStream(Imagepath, FileMode.Create));
                product.ImagePath = product.ProductImage.FileName;
            }

            if (!ModelState.IsValid) {
               
                int id;
                if (_db.Products.Count() == 0)
                    id = 0;
                else
                    id = _db.Products.Max(x => x.Id) + 1;
                product.Id = id;
                return View(product);
            }
            _db.Products.Add(product);
            _db.SaveChanges();
            
            return RedirectToAction("index");
        }
        #region
        
        public IActionResult GetAllData()
        {
           
    
            return View(_db.Products);

        }
        #endregion
        #region delete
        public IActionResult Delete(int id)
        {
            Product prod = _db.Products.FirstOrDefault(x => x.Id == id); //get id i wanna delete
           _db.Products.Remove(prod);
            _db.SaveChanges();
            return RedirectToAction("GetAllData");
        }
		#endregion
		#region edit
		[Authorize(Roles = RL.RoleAdmin)]
		public IActionResult EditProduct(int id)
        {
            Product product = _db.Products.FirstOrDefault(x => x.Id == id);
            _db.SaveChanges();
            return View(product);

        }
        [HttpPost]
		[Authorize(Roles = RL.RoleAdmin)]
		public IActionResult EditProduct(Product product)
        {
            if (!ModelState.IsValid)
            {
            
                return View(product);
            }
            else
            {
                Product pro = _db.Products.SingleOrDefault(x => x.Id == product.Id);
                pro.Name = product.Name;
                pro.Description = product.Description;
                pro.Price = product.Price;
                pro.Quantity = product.Quantity;
                _db.Update(pro);
                _db.SaveChanges();
                return RedirectToAction("GetAllData");
            }
           
        }
		#endregion
		public IActionResult ContactUs()
		{
            List<Contact> conts = _db.Contacts.ToList();
           
            return View(conts);
            

		}
        [HttpPost]
        public IActionResult Blogs(Blogy b)
        {
            if (b.BlogImage != null)
            {
                string ImageFolder = Path.Combine(host.WebRootPath, "images");
                string Imagepath = Path.Combine(ImageFolder, b.BlogImage.FileName);
                b.BlogImage.CopyTo(new FileStream(Imagepath, FileMode.Create));
                b.ImagesPath = b.BlogImage.FileName;
            }
           
           
            _db.blogs.Add(b);
 b.BlogDate = DateTime.Now;
            _db.SaveChanges();
            return RedirectToAction("index");
        }
        public IActionResult Blogs ()
        {
            return View();
        }
        public IActionResult ViewBlog()
        {
            return View(_db.blogs);
        }
        #region deleteblog
        public IActionResult DeleteBlog(int id)
        {
            Blogy blog = _db.blogs.FirstOrDefault(x => x.BlogId == id); //get id i wanna delete
            _db.blogs.Remove(blog);
            _db.SaveChanges();
            return RedirectToAction("ViewBlog");
        }
        #endregion
        #region editblog
        public IActionResult EditBlog(int id)
        {
            Blogy blog = _db.blogs.FirstOrDefault(x => x.BlogId == id);
            _db.SaveChanges();
            return View(blog);

        }
        [HttpPost]
        public IActionResult EditBlog(Blogy blogy)
        {
           

                Blogy blogg = _db.blogs.SingleOrDefault(x => x.BlogId == blogy.BlogId);
                blogg.Title = blogy.Title;
                blogg.Description = blogy.Description;
                blogg.Author = blogy.Author;

                _db.Update(blogg);
                _db.SaveChanges();
                return RedirectToAction("ViewBlog");
            

        }
        #endregion
    }
}

WebApplication4/Views/Shared/_DashBoard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication5.styles.css" asp-append-version="true" />
    <!----======== CSS ======== -->
    <link rel="stylesheet" href="~/css/DBcss/style.css">

    <!----===== Iconscout CSS ===== -->
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">

    <title>Admin Dashboard Panel</title>
</head>
<body>
    <nav>
        <div class="logo-name">
            <div class="logo-image">
                <img src="images/logo.png" alt="">
            </div>

            <span class="logo_name">Furni</span>
        </div>

        <div class="menu-items">
            <ul class="nav-links">
                <li>
                    <a asp-action="Index" asp-controller="Home">
                        <i class="uil uil-estate"></i>
                        <span class="link-name">Home</span>
                    </a>
                </li>
                <li>
                    <a asp-action="AddProduct">
                        <i class="uil uil-files-landscapes"></i>
                        <span class="link-name">Add Product</span>
                    </a>
                </li>
                <li>
                    <a asp-action="GetAllData">
                        <i class="uil uil-chart"></i>
                        <span class="link-name">View Product</span>
                    </a>
                </li>
                <li>
                    <a asp-action="ContactUs">
                        <i class="uil uil-thumbs-up"></i>
                        <span class="link-name">View Contact</span>
                    </a>
                </li>
                <li>
                    <a asp-action="Blogs">
                        <i class="uil uil-thumbs-up"></i>
                        <span class="link-name">Add Blog</span>
                    </a>
                </li>

                <li>
                    <a asp-action="ViewBlog">
                        <i class="uil uil-comments"></i>
                        <span class="link-name">View Blog</span>
                    </a>
                </li>
            </ul>

            <ul class="logout-mode">
                <li>
                    <a href="#">
                        <i class="uil uil-signout"></i>
                        <span class="link-name">Logout</span>
                    </a>
                </li>

                <li class="mode">
                    <a href="#">
                        <i class="uil uil-moon"></i>
                        <span class="link-name">Dark Mode</span>
                    </a>

                    <div class="mode-toggle">
                        <span class="switch"></span>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <section class="dashboard">
        <div class="top">
            <i class="uil uil-bars sidebar-toggle"></i>

            <div class="search-box">
                <i class="uil uil-search"></i>
                <input type="text" placeholder="Search here...">
            </div>

            <img src="images/profile.jpg" alt="">
        </div>

        <div class="dash-content">
            @RenderBody()
        </div>

    </section>

    <script src="~/js/DBjs/script.js"></script>
</body>
</html>

WebApplication4/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="author" content="Untree.co">
	<link rel="shortcut icon" href="favicon.png">

	<meta name="description" content="" />
	<meta name="keywords" content="bootstrap, bootstrap4" />

	<!-- Bootstrap CSS -->
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
	<link href="~/css/css/tiny-slider.css" rel="stylesheet">
	<link href="~/css/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/WebApplication4.styles.css" asp-append-version="true" />
	<title>Furni Free Bootstrap 5 Template for Furniture and Interior Design Websites by Untree.co </title>
</head>

<body>

	<!-- Start Header/Navigation -->
	<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

		<div class="container">
			<a class="navbar-brand" href="index.html">Furni<span>.</span></a>

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarsFurni">
				<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
					<li class="nav-item active">
						<a class="nav-link" asp-controller="Home" asp-action="index">Home</a>
					</li>
					<li><a class="nav-link" asp-controller="Shopy" asp-action="Shop">Shop</a></li>
					<li><a class="nav-link" asp-controller="Shopy" asp-action="AboutUs">About us</a></li>
					<li><a class="nav-link" asp-controller="Shopy" asp-action="Service">Services</a></li>
					<li><a class="nav-link" asp-controller="Shopy" asp-action="blog">Blog</a></li>
					<li><a class="nav-link" asp-controller="Shopy" asp-action="Contactt">Contact us</a></li>
					<li><a class="nav-link" asp-controller="DashBoard" asp-action="index">DashBoard</a></li>
                   
				</ul>

				<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
					@* 					<li><a class="nav-link" href="#"><img src="images/user.svg"></a></li>

					*@
                    <li class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0"><partial name="_LoginPartial" /></li>
					<li><a class="nav-link" asp-action="Cart" asp-controller="Shopy"><img src="~/images/cart.svg"></a></li>
				</ul>
			</div>
		</div>

	</nav>
	<!-- End Header/Navigation -->
	


    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

	<!-- Start Footer Section -->
	<footer class="footer-section">
		<div class="container relative">

			<div class="sofa-img">
				<img src="~/images/sofa.png" alt="Image" class="img-fluid">
			</div>

		@* 	<div class="row">
				<div class="col-lg-8">
					<div class="subscription-form">
						<h3 class="d-flex align-items-center"><span class="me-1"><img src="~/images/envelope-outline.svg" alt="Image" class="img-fluid"></span><span>Subscribe to Newsletter</span></h3>

						<form action="#" class="row g-3">
							<div class="col-auto">
								<input type="text" class="form-control" placeholder="Enter your name">
							</div>
							<div class="col-auto">
								<input type="email" class="form-control" placeholder="Enter your email">
							</div>
							<div class="col-auto">
								<button class="btn btn-primary">
									<span class="fa fa-paper-plane"></span>
								</button>
							</div>
						</form>

					</div>
				</div>
			</div> *@

			<div class="row g-5 mb-5">
				<div class="col-lg-4">
					<div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">Furni<span>.</span></a></div>
					<p class="mb-4">Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant</p>

					<ul class="list-unstyled custom-social">
						<li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
						<li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
						<li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
						<li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
					</ul>
				</div>

				<div class="col-lg-8">
					<div class="row links-wrap">
						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">About us</a></li>
								<li><a href="#">Services</a></li>
								<li><a href="#">Blog</a></li>
								<li><a href="#">Contact us</a></li>
							</ul>
						</div>

						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">Support</a></li>
								<li><a href="#">Knowledge base</a></li>
								<li><a href="#">Live chat</a></li>
							</ul>
						</div>

						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">Jobs</a></li>
								<li><a href="#">Our team</a></li>
								<li><a href="#">Leadership</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>

						<div class="col-6 col-sm-6 col-md-3">
							<ul class="list-unstyled">
								<li><a href="#">Nordic Chair</a></li>
								<li><a href="#">Kruzo Aero</a></li>
								<li><a href="#">Ergonomic Chair</a></li>
							</ul>
						</div>
					</div>
				</div>

			</div>

			<div class="border-top copyright">
				<div class="row pt-4">
					<div class="col-lg-6">
						<p class="mb-2 text-center text-lg-start">
							Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://untree.co">Untree.co</a> Distributed By <a hreff="https://themewagon.com">ThemeWagon</a>  <!-- License information: https://untree.co/license/ -->
						</p>
					</div>

					<div class="col-lg-6 text-center text-lg-end">
						<ul class="list-unstyled d-inline-flex ms-auto">
							<li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
							<li><a href="#">Privacy Policy</a></li>
						</ul>
					</div>

				</div>
			</div>

		</div>
	</footer>
	<!-- End Footer Section -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
 </body>
 </html>